defmodule NucleusWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nucleus

  # The session is stored in the cookie, signed and encrypted (`encryption_salt`):
  # since AUTH-S1 it holds the signed-in user's email, and during sign-in the
  # PKCE verifier, which is meant to stay private. Encryption is keyed from
  # `secret_key_base`; the salts only separate the two derived keys and are not
  # secret. Changing either salt signs everyone out.
  #
  # `secure: true` keeps the cookie off plain HTTP. `config/dev.exs` and
  # `config/test.exs` turn it off (dev is served over http://localhost); every
  # other environment gets `config/config.exs`'s `true`. `Application.compile_env!`
  # has no fallback on purpose, so a missing setting is a compile error rather
  # than a quietly insecure cookie.
  @session_options [
    store: :cookie,
    key: "_nucleus_key",
    signing_salt: "HS0ov6Hz",
    encryption_salt: "Qn3vYk8xT2",
    same_site: "Lax",
    secure: Application.compile_env!(:nucleus, :session_cookie_secure)
  ]

  # :x_headers is declared here (EN-6) so NucleusWeb.ScopeHook can read
  # X-Forwarded-For via get_connect_info/2 on a connected LiveView socket —
  # the initial Plug.Conn no longer exists once the socket is live, and this
  # is the only place the header is still available.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:x_headers, session: @session_options]],
    longpoll: [connect_info: [:x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :nucleus,
    gzip: not code_reloading?,
    only: NucleusWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug NucleusWeb.Router
end
