import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :nucleus, NucleusWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Ju7WFqUb7nvTwQPqdM15mRGih6NQitOXIUFevNBvnlxJUBFmXUcq+74Q7TyQ3DhM",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:nucleus, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:nucleus, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :nucleus, dev_routes: true

# Run every boundary against its local implementation, so a fresh clone starts
# with no AWS role and no tenant API reachable. Override per boundary with
# SECRETS_BACKEND=real / TENANT_API_BACKEND=real / M2M_BACKEND=real /
# NOMAD_JOBS_BACKEND=real / NOMAD_VARS_BACKEND=real (see config/runtime.exs).
config :nucleus, :backends,
  secrets: Nucleus.Secrets.Store.Local,
  tenant_api: Nucleus.TenantApi.Local,
  m2m: Nucleus.M2M.Clients.Local,
  nomad_jobs: Nucleus.NomadJobs.Local,
  nomad_vars: Nucleus.NomadVars.Store.Local

# Deploy-time cluster/deployment segments of the Parameter Store path (see
# lib/nucleus/secrets/path.ex). Hardcoded here rather than sourced from an env
# var, matching the TENANT_NAMESPACE precedent — no env var needed locally.
config :nucleus, Nucleus.Secrets.Path,
  cluster_name: "local-cluster",
  deployment_name: "local-deployment"

# The M2M deny-list's default suffix set, hardcoded rather than sourced from
# M2M_DENY_SUFFIXES — same TENANT_NAMESPACE precedent as above. This is the
# prototype's actual Terraform value (M2M-S1 Decision 2), not a placeholder,
# so a fresh clone exercises the deny-list against real values.
config :nucleus, Nucleus.M2M.DenyList,
  suffixes: ~w(-labops-ui -faas-api -faas-ui -device_grant -orange -nucleus)

# Human-readable audit records for local development. AUD-A05 requires the
# set of recorded events to be unchanged by the format — only the encoding
# differs here, not which events are audited.
config :nucleus, Nucleus.Audit, format: :text

# Auth is disabled by default (see config/config.exs); this is the dev
# identity Nucleus.Scope.Provider.Disabled assigns to every session. With
# AUTH_ENABLED=true this is unused — email and scopes come from the minted
# JWT instead (EN-6, deferred; see docs/adr/0005-deferred-authentication.md).
config :nucleus, Nucleus.Scope.Provider.Disabled,
  email: "dev@example.com",
  scopes: []

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
